[build-system]
requires = ["setuptools>=61.0", "aiohttp>=3.9.0", "python-dotenv==1.0.0", "tiktoken==0.5.1", "httpx==0.25.1"]
build-backend = "setuptools.build_meta"

[project]
name="lionagi"
version=__version__
author="HaiyangLi"
author_email="ocean@lionagi.ai"
description="Towards automated general intelligence."
packages=setuptools.find_packages(include=["lionagi*"])
install_requires=install_requires
classifiers=[
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache 2.0 License",
    "Operating System :: OS Independent",
]
python_requires=">=3.9"

[project.urls]
Homepage = "https://github.com/pypa/sampleproject"
Issues = "https://github.com/pypa/sampleproject/issues"
